# Generated by Django 4.2.3 on 2023-11-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('chatid', models.CharField(db_index=True, max_length=301, primary_key=True, serialize=False, unique=True, verbose_name='id')),
            ],
        ),
    ]
