# Generated by Django 4.2.3 on 2023-10-17 16:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, validators=[core.models.password_validator], verbose_name='password'),
        ),
    ]
